name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configurar JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Compilar com Maven
      run: mvn -B compile assembly:single --file "milkshakestore/pom.xml"
    - name: Disponibilizar arquivo compilado
      run: mkdir staging && cp ./milkshakestore/target/*.jar staging
    - uses: actions/upload-artifact@v3
      with:
        name: milkshakestore-compiled
        path: staging
